### ISSUE TITLE
Rename crosswalks to linkage-tables everywhere

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-workflows-runner#34]
A rebranding of crosswalks has been ordered. We need to find all occurrences of crosswalk and replace it with 'linkage-table'. Please use common sense but some examples might be:

* crosswalk-tables => linkage-tables
* CROSSWALK => LINKAGE_TABLE
* CROSSWALK_TABLE => LINKAGE_TABLE
* crosswalkTables => linkageTables

Let me know if you have any questions. This change does not need to interrupt the v0.7 run. It can happen after/at a safe time.

**Comment by andreasbueckle** [comment]
@bherr2 
Update: We agreed not to implement this. Close as not planned?
